// Generated by gencpp from file ros_tutorial/TutorialSineWaveInput.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_TUTORIALSINEWAVEINPUT_H
#define ROS_TUTORIAL_MESSAGE_TUTORIALSINEWAVEINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct TutorialSineWaveInput_
{
  typedef TutorialSineWaveInput_<ContainerAllocator> Type;

  TutorialSineWaveInput_()
    : period(0.0)
    , noise_standard_deviation(0.0)
    , amplitude(0.0)  {
    }
  TutorialSineWaveInput_(const ContainerAllocator& _alloc)
    : period(0.0)
    , noise_standard_deviation(0.0)
    , amplitude(0.0)  {
  (void)_alloc;
    }



   typedef double _period_type;
  _period_type period;

   typedef double _noise_standard_deviation_type;
  _noise_standard_deviation_type noise_standard_deviation;

   typedef double _amplitude_type;
  _amplitude_type amplitude;





  typedef boost::shared_ptr< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialSineWaveInput_

typedef ::ros_tutorial::TutorialSineWaveInput_<std::allocator<void> > TutorialSineWaveInput;

typedef boost::shared_ptr< ::ros_tutorial::TutorialSineWaveInput > TutorialSineWaveInputPtr;
typedef boost::shared_ptr< ::ros_tutorial::TutorialSineWaveInput const> TutorialSineWaveInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator1> & lhs, const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator2> & rhs)
{
  return lhs.period == rhs.period &&
    lhs.noise_standard_deviation == rhs.noise_standard_deviation &&
    lhs.amplitude == rhs.amplitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator1> & lhs, const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cd899687a4aae1254b2449fcada7c3e";
  }

  static const char* value(const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cd899687a4aae12ULL;
  static const uint64_t static_value2 = 0x54b2449fcada7c3eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/TutorialSineWaveInput";
  }

  static const char* value(const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 period\n"
"float64 noise_standard_deviation\n"
"float64 amplitude\n"
;
  }

  static const char* value(const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.period);
      stream.next(m.noise_standard_deviation);
      stream.next(m.amplitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialSineWaveInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::TutorialSineWaveInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "period: ";
    Printer<double>::stream(s, indent + "  ", v.period);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "noise_standard_deviation: ";
    Printer<double>::stream(s, indent + "  ", v.noise_standard_deviation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "amplitude: ";
    Printer<double>::stream(s, indent + "  ", v.amplitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_TUTORIALSINEWAVEINPUT_H
