// Generated by gencpp from file ros_tutorial/TutorialVehicleState.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_TUTORIALVEHICLESTATE_H
#define ROS_TUTORIAL_MESSAGE_TUTORIALVEHICLESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct TutorialVehicleState_
{
  typedef TutorialVehicleState_<ContainerAllocator> Type;

  TutorialVehicleState_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , steering_angle(0.0)  {
    }
  TutorialVehicleState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialVehicleState_

typedef ::ros_tutorial::TutorialVehicleState_<std::allocator<void> > TutorialVehicleState;

typedef boost::shared_ptr< ::ros_tutorial::TutorialVehicleState > TutorialVehicleStatePtr;
typedef boost::shared_ptr< ::ros_tutorial::TutorialVehicleState const> TutorialVehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator1> & lhs, const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator1> & lhs, const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b6a4b07a703d3ad2519e2fcecc39a07";
  }

  static const char* value(const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b6a4b07a703d3adULL;
  static const uint64_t static_value2 = 0x2519e2fcecc39a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/TutorialVehicleState";
  }

  static const char* value(const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 steering_angle\n"
;
  }

  static const char* value(const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialVehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::TutorialVehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::TutorialVehicleState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_TUTORIALVEHICLESTATE_H
