// Generated by gencpp from file dcas_msgs/Lane.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_LANE_H
#define DCAS_MSGS_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct Lane_
{
  typedef Lane_<ContainerAllocator> Type;

  Lane_()
    : header()
    , id(0)
    , lane_lines()
    , lane_type(0)  {
    }
  Lane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , lane_lines(_alloc)
    , lane_type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _lane_lines_type;
  _lane_lines_type lane_lines;

   typedef uint8_t _lane_type_type;
  _lane_type_type lane_type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TYPE_UNKNOWN)
  #undef TYPE_UNKNOWN
#endif
#if defined(_WIN32) && defined(TYPE_WHITE_SOLID)
  #undef TYPE_WHITE_SOLID
#endif
#if defined(_WIN32) && defined(TYPE_WHITE_DASHED)
  #undef TYPE_WHITE_DASHED
#endif
#if defined(_WIN32) && defined(TYPE_YELLOW_SOLID)
  #undef TYPE_YELLOW_SOLID
#endif
#if defined(_WIN32) && defined(TYPE_YELLOW_DASHED)
  #undef TYPE_YELLOW_DASHED
#endif
#if defined(_WIN32) && defined(TYPE_DOUBLE_YELLOW_SOLID)
  #undef TYPE_DOUBLE_YELLOW_SOLID
#endif

  enum {
    TYPE_UNKNOWN = 0u,
    TYPE_WHITE_SOLID = 1u,
    TYPE_WHITE_DASHED = 2u,
    TYPE_YELLOW_SOLID = 3u,
    TYPE_YELLOW_DASHED = 4u,
    TYPE_DOUBLE_YELLOW_SOLID = 5u,
  };


  typedef boost::shared_ptr< ::dcas_msgs::Lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::Lane_<ContainerAllocator> const> ConstPtr;

}; // struct Lane_

typedef ::dcas_msgs::Lane_<std::allocator<void> > Lane;

typedef boost::shared_ptr< ::dcas_msgs::Lane > LanePtr;
typedef boost::shared_ptr< ::dcas_msgs::Lane const> LaneConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::Lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::Lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::Lane_<ContainerAllocator1> & lhs, const ::dcas_msgs::Lane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.lane_lines == rhs.lane_lines &&
    lhs.lane_type == rhs.lane_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::Lane_<ContainerAllocator1> & lhs, const ::dcas_msgs::Lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::Lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::Lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::Lane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::Lane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7404a3f5e4db4c5f96339c55f4901f6";
  }

  static const char* value(const ::dcas_msgs::Lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7404a3f5e4db4c5ULL;
  static const uint64_t static_value2 = 0xf96339c55f4901f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/Lane";
  }

  static const char* value(const ::dcas_msgs::Lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 id\n"
"# For simplicity use 2D points in map frame\n"
"geometry_msgs/Point32[] lane_lines\n"
"\n"
"# Lane type definitions\n"
"uint8 TYPE_UNKNOWN=0\n"
"uint8 TYPE_WHITE_SOLID=1\n"
"uint8 TYPE_WHITE_DASHED=2\n"
"uint8 TYPE_YELLOW_SOLID=3\n"
"uint8 TYPE_YELLOW_DASHED=4\n"
"uint8 TYPE_DOUBLE_YELLOW_SOLID=5\n"
"uint8 lane_type\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::dcas_msgs::Lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::Lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.lane_lines);
      stream.next(m.lane_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::Lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::Lane_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lane_lines: ";
    if (v.lane_lines.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.lane_lines.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.lane_lines[i]);
    }
    if (v.lane_lines.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lane_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_LANE_H
