// Generated by gencpp from file dcas_msgs/Object.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_OBJECT_H
#define DCAS_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Point32.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : header()
    , id(0)
    , type(0)
    , pose()
    , size()
    , twist()
    , geom_type(0)
    , footprint()
    , height(0.0)  {
    }
  Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , type(0)
    , pose(_alloc)
    , size(_alloc)
    , twist(_alloc)
    , geom_type(0)
    , footprint(_alloc)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _type_type;
  _type_type type;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef uint8_t _geom_type_type;
  _geom_type_type geom_type;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _footprint_type;
  _footprint_type footprint;

   typedef float _height_type;
  _height_type height;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GEOM_BOX)
  #undef GEOM_BOX
#endif
#if defined(_WIN32) && defined(GEOM_POLYGON)
  #undef GEOM_POLYGON
#endif
#if defined(_WIN32) && defined(LABEL_UNKNOWN)
  #undef LABEL_UNKNOWN
#endif
#if defined(_WIN32) && defined(LABEL_VEHICLE)
  #undef LABEL_VEHICLE
#endif
#if defined(_WIN32) && defined(LABEL_PEDESTRIAN)
  #undef LABEL_PEDESTRIAN
#endif
#if defined(_WIN32) && defined(LABEL_CYCLIST)
  #undef LABEL_CYCLIST
#endif
#if defined(_WIN32) && defined(LABEL_TRAFFIC_LIGHT)
  #undef LABEL_TRAFFIC_LIGHT
#endif
#if defined(_WIN32) && defined(LABEL_TRAFFIC_SIGN)
  #undef LABEL_TRAFFIC_SIGN
#endif
#if defined(_WIN32) && defined(LABEL_GUARDRAIL)
  #undef LABEL_GUARDRAIL
#endif
#if defined(_WIN32) && defined(LABEL_BUILDING)
  #undef LABEL_BUILDING
#endif

  enum {
    GEOM_BOX = 0u,
    GEOM_POLYGON = 1u,
    LABEL_UNKNOWN = 0u,
    LABEL_VEHICLE = 1u,
    LABEL_PEDESTRIAN = 2u,
    LABEL_CYCLIST = 3u,
    LABEL_TRAFFIC_LIGHT = 10u,
    LABEL_TRAFFIC_SIGN = 11u,
    LABEL_GUARDRAIL = 12u,
    LABEL_BUILDING = 13u,
  };


  typedef boost::shared_ptr< ::dcas_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::dcas_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::dcas_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::dcas_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::Object_<ContainerAllocator1> & lhs, const ::dcas_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.pose == rhs.pose &&
    lhs.size == rhs.size &&
    lhs.twist == rhs.twist &&
    lhs.geom_type == rhs.geom_type &&
    lhs.footprint == rhs.footprint &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::Object_<ContainerAllocator1> & lhs, const ::dcas_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09a2b3417990e01d5598408cceb6c012";
  }

  static const char* value(const ::dcas_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09a2b3417990e01dULL;
  static const uint64_t static_value2 = 0x5598408cceb6c012ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/Object";
  }

  static const char* value(const ::dcas_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Generic object description for environment/perception\n"
"std_msgs/Header header\n"
"uint32 id\n"
"uint8 type\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 size  # For GEOM_BOX (fallback; width(x), depth(y), height(z))\n"
"geometry_msgs/Twist twist\n"
"\n"
"# Geometry shape (to visualize true footprint, e.g., buildings)\n"
"uint8 GEOM_BOX=0\n"
"uint8 GEOM_POLYGON=1\n"
"uint8 geom_type\n"
"geometry_msgs/Point32[] footprint  # Map-frame polygon (z ignored); closed by convention (first==last not required)\n"
"float32 height  # For GEOM_POLYGON, extruded height (meters)\n"
"\n"
"# Type labels (keep minimal and course-focused)\n"
"uint8 LABEL_UNKNOWN=0\n"
"uint8 LABEL_VEHICLE=1\n"
"uint8 LABEL_PEDESTRIAN=2\n"
"uint8 LABEL_CYCLIST=3\n"
"uint8 LABEL_TRAFFIC_LIGHT=10\n"
"uint8 LABEL_TRAFFIC_SIGN=11\n"
"uint8 LABEL_GUARDRAIL=12\n"
"uint8 LABEL_BUILDING=13\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::dcas_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.pose);
      stream.next(m.size);
      stream.next(m.twist);
      stream.next(m.geom_type);
      stream.next(m.footprint);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::Object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "twist: ";
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "geom_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.geom_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "footprint: ";
    if (v.footprint.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.footprint.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.footprint[i]);
    }
    if (v.footprint.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_OBJECT_H
