// Generated by gencpp from file dcas_msgs/ObjectArray.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_OBJECTARRAY_H
#define DCAS_MSGS_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dcas_msgs/Object.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : header()
    , objects()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dcas_msgs::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dcas_msgs::Object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::dcas_msgs::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::dcas_msgs::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::dcas_msgs::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::dcas_msgs::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a148595d8713c4b90d42f0a686db8d9";
  }

  static const char* value(const ::dcas_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a148595d8713c4bULL;
  static const uint64_t static_value2 = 0x90d42f0a686db8d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/ObjectArray";
  }

  static const char* value(const ::dcas_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"dcas_msgs/Object[] objects\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dcas_msgs/Object\n"
"# Generic object description for environment/perception\n"
"std_msgs/Header header\n"
"uint32 id\n"
"uint8 type\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 size  # For GEOM_BOX (fallback; width(x), depth(y), height(z))\n"
"geometry_msgs/Twist twist\n"
"\n"
"# Geometry shape (to visualize true footprint, e.g., buildings)\n"
"uint8 GEOM_BOX=0\n"
"uint8 GEOM_POLYGON=1\n"
"uint8 geom_type\n"
"geometry_msgs/Point32[] footprint  # Map-frame polygon (z ignored); closed by convention (first==last not required)\n"
"float32 height  # For GEOM_POLYGON, extruded height (meters)\n"
"\n"
"# Type labels (keep minimal and course-focused)\n"
"uint8 LABEL_UNKNOWN=0\n"
"uint8 LABEL_VEHICLE=1\n"
"uint8 LABEL_PEDESTRIAN=2\n"
"uint8 LABEL_CYCLIST=3\n"
"uint8 LABEL_TRAFFIC_LIGHT=10\n"
"uint8 LABEL_TRAFFIC_SIGN=11\n"
"uint8 LABEL_GUARDRAIL=12\n"
"uint8 LABEL_BUILDING=13\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::dcas_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::ObjectArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::dcas_msgs::Object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_OBJECTARRAY_H
