// Generated by gencpp from file dcas_msgs/RadarDetectionArray.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_RADARDETECTIONARRAY_H
#define DCAS_MSGS_MESSAGE_RADARDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dcas_msgs/RadarDetection.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct RadarDetectionArray_
{
  typedef RadarDetectionArray_<ContainerAllocator> Type;

  RadarDetectionArray_()
    : header()
    , detections()  {
    }
  RadarDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dcas_msgs::RadarDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dcas_msgs::RadarDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct RadarDetectionArray_

typedef ::dcas_msgs::RadarDetectionArray_<std::allocator<void> > RadarDetectionArray;

typedef boost::shared_ptr< ::dcas_msgs::RadarDetectionArray > RadarDetectionArrayPtr;
typedef boost::shared_ptr< ::dcas_msgs::RadarDetectionArray const> RadarDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fda954c0e5481cab05327c93c07e585f";
  }

  static const char* value(const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfda954c0e5481cabULL;
  static const uint64_t static_value2 = 0x05327c93c07e585fULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/RadarDetectionArray";
  }

  static const char* value(const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"dcas_msgs/RadarDetection[] detections\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dcas_msgs/RadarDetection\n"
"std_msgs/Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"float32 rcs\n"
"float32 range\n"
"float32 doppler\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::RadarDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::RadarDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::dcas_msgs::RadarDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_RADARDETECTIONARRAY_H
