// Generated by gencpp from file dcas_msgs/RadarDetection.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_RADARDETECTION_H
#define DCAS_MSGS_MESSAGE_RADARDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct RadarDetection_
{
  typedef RadarDetection_<ContainerAllocator> Type;

  RadarDetection_()
    : header()
    , position()
    , velocity()
    , rcs(0.0)
    , range(0.0)
    , doppler(0.0)  {
    }
  RadarDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , rcs(0.0)
    , range(0.0)
    , doppler(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef float _rcs_type;
  _rcs_type rcs;

   typedef float _range_type;
  _range_type range;

   typedef float _doppler_type;
  _doppler_type doppler;





  typedef boost::shared_ptr< ::dcas_msgs::RadarDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::RadarDetection_<ContainerAllocator> const> ConstPtr;

}; // struct RadarDetection_

typedef ::dcas_msgs::RadarDetection_<std::allocator<void> > RadarDetection;

typedef boost::shared_ptr< ::dcas_msgs::RadarDetection > RadarDetectionPtr;
typedef boost::shared_ptr< ::dcas_msgs::RadarDetection const> RadarDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::RadarDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::RadarDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::RadarDetection_<ContainerAllocator1> & lhs, const ::dcas_msgs::RadarDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.rcs == rhs.rcs &&
    lhs.range == rhs.range &&
    lhs.doppler == rhs.doppler;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::RadarDetection_<ContainerAllocator1> & lhs, const ::dcas_msgs::RadarDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::RadarDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::RadarDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::RadarDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dbfcaf32fc075de68e731ba17300947";
  }

  static const char* value(const ::dcas_msgs::RadarDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dbfcaf32fc075deULL;
  static const uint64_t static_value2 = 0x68e731ba17300947ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/RadarDetection";
  }

  static const char* value(const ::dcas_msgs::RadarDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"float32 rcs\n"
"float32 range\n"
"float32 doppler\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dcas_msgs::RadarDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.rcs);
      stream.next(m.range);
      stream.next(m.doppler);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::RadarDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::RadarDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rcs: ";
    Printer<float>::stream(s, indent + "  ", v.rcs);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "doppler: ";
    Printer<float>::stream(s, indent + "  ", v.doppler);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_RADARDETECTION_H
