// Generated by gencpp from file dcas_msgs/TrafficLightArray.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_TRAFFICLIGHTARRAY_H
#define DCAS_MSGS_MESSAGE_TRAFFICLIGHTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dcas_msgs/TrafficLight.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct TrafficLightArray_
{
  typedef TrafficLightArray_<ContainerAllocator> Type;

  TrafficLightArray_()
    : header()
    , lights()  {
    }
  TrafficLightArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lights(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dcas_msgs::TrafficLight_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dcas_msgs::TrafficLight_<ContainerAllocator> >> _lights_type;
  _lights_type lights;





  typedef boost::shared_ptr< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightArray_

typedef ::dcas_msgs::TrafficLightArray_<std::allocator<void> > TrafficLightArray;

typedef boost::shared_ptr< ::dcas_msgs::TrafficLightArray > TrafficLightArrayPtr;
typedef boost::shared_ptr< ::dcas_msgs::TrafficLightArray const> TrafficLightArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::TrafficLightArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::TrafficLightArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficLightArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lights == rhs.lights;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::TrafficLightArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficLightArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae3faa55d431d7df7116cd9eb141ea12";
  }

  static const char* value(const ::dcas_msgs::TrafficLightArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae3faa55d431d7dfULL;
  static const uint64_t static_value2 = 0x7116cd9eb141ea12ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/TrafficLightArray";
  }

  static const char* value(const ::dcas_msgs::TrafficLightArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"dcas_msgs/TrafficLight[] lights\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dcas_msgs/TrafficLight\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"uint8 state\n"
"\n"
"uint8 RED=0\n"
"uint8 YELLOW=1\n"
"uint8 GREEN=2\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dcas_msgs::TrafficLightArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lights);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::TrafficLightArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::TrafficLightArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lights: ";
    if (v.lights.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.lights.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::dcas_msgs::TrafficLight_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.lights[i]);
    }
    if (v.lights.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_TRAFFICLIGHTARRAY_H
