// Generated by gencpp from file dcas_msgs/TrafficSignArray.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_TRAFFICSIGNARRAY_H
#define DCAS_MSGS_MESSAGE_TRAFFICSIGNARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dcas_msgs/TrafficSign.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct TrafficSignArray_
{
  typedef TrafficSignArray_<ContainerAllocator> Type;

  TrafficSignArray_()
    : header()
    , signs()  {
    }
  TrafficSignArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::dcas_msgs::TrafficSign_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::dcas_msgs::TrafficSign_<ContainerAllocator> >> _signs_type;
  _signs_type signs;





  typedef boost::shared_ptr< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSignArray_

typedef ::dcas_msgs::TrafficSignArray_<std::allocator<void> > TrafficSignArray;

typedef boost::shared_ptr< ::dcas_msgs::TrafficSignArray > TrafficSignArrayPtr;
typedef boost::shared_ptr< ::dcas_msgs::TrafficSignArray const> TrafficSignArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::TrafficSignArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::TrafficSignArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signs == rhs.signs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::TrafficSignArray_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficSignArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06d9b79e9aad276f858f3ff080587c81";
  }

  static const char* value(const ::dcas_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06d9b79e9aad276fULL;
  static const uint64_t static_value2 = 0x858f3ff080587c81ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/TrafficSignArray";
  }

  static const char* value(const ::dcas_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"dcas_msgs/TrafficSign[] signs\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dcas_msgs/TrafficSign\n"
"std_msgs/Header header\n"
"uint32 id\n"
"geometry_msgs/Pose pose\n"
"uint8 sign_class\n"
"\n"
"# Traffic sign classes\n"
"uint8 CLASS_UNKNOWN=0\n"
"uint8 CLASS_STOP=1\n"
"uint8 CLASS_YIELD=2\n"
"uint8 CLASS_SPEED_LIMIT_30=3\n"
"uint8 CLASS_SPEED_LIMIT_50=4\n"
"uint8 CLASS_SPEED_LIMIT_60=5\n"
"uint8 CLASS_SPEED_LIMIT_80=6\n"
"uint8 CLASS_NO_ENTRY=7\n"
"uint8 CLASS_NO_PARKING=8\n"
"uint8 CLASS_PEDESTRIAN_CROSSING=9\n"
"uint8 CLASS_SCHOOL_ZONE=10\n"
"uint8 CLASS_CONSTRUCTION=11\n"
"uint8 CLASS_TURN_LEFT=12\n"
"uint8 CLASS_TURN_RIGHT=13\n"
"uint8 CLASS_GO_STRAIGHT=14\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dcas_msgs::TrafficSignArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSignArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::TrafficSignArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::TrafficSignArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "signs: ";
    if (v.signs.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.signs.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::dcas_msgs::TrafficSign_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.signs[i]);
    }
    if (v.signs.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_TRAFFICSIGNARRAY_H
