// Generated by gencpp from file dcas_msgs/TrafficSign.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_TRAFFICSIGN_H
#define DCAS_MSGS_MESSAGE_TRAFFICSIGN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct TrafficSign_
{
  typedef TrafficSign_<ContainerAllocator> Type;

  TrafficSign_()
    : header()
    , id(0)
    , pose()
    , sign_class(0)  {
    }
  TrafficSign_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , pose(_alloc)
    , sign_class(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _sign_class_type;
  _sign_class_type sign_class;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CLASS_UNKNOWN)
  #undef CLASS_UNKNOWN
#endif
#if defined(_WIN32) && defined(CLASS_STOP)
  #undef CLASS_STOP
#endif
#if defined(_WIN32) && defined(CLASS_YIELD)
  #undef CLASS_YIELD
#endif
#if defined(_WIN32) && defined(CLASS_SPEED_LIMIT_30)
  #undef CLASS_SPEED_LIMIT_30
#endif
#if defined(_WIN32) && defined(CLASS_SPEED_LIMIT_50)
  #undef CLASS_SPEED_LIMIT_50
#endif
#if defined(_WIN32) && defined(CLASS_SPEED_LIMIT_60)
  #undef CLASS_SPEED_LIMIT_60
#endif
#if defined(_WIN32) && defined(CLASS_SPEED_LIMIT_80)
  #undef CLASS_SPEED_LIMIT_80
#endif
#if defined(_WIN32) && defined(CLASS_NO_ENTRY)
  #undef CLASS_NO_ENTRY
#endif
#if defined(_WIN32) && defined(CLASS_NO_PARKING)
  #undef CLASS_NO_PARKING
#endif
#if defined(_WIN32) && defined(CLASS_PEDESTRIAN_CROSSING)
  #undef CLASS_PEDESTRIAN_CROSSING
#endif
#if defined(_WIN32) && defined(CLASS_SCHOOL_ZONE)
  #undef CLASS_SCHOOL_ZONE
#endif
#if defined(_WIN32) && defined(CLASS_CONSTRUCTION)
  #undef CLASS_CONSTRUCTION
#endif
#if defined(_WIN32) && defined(CLASS_TURN_LEFT)
  #undef CLASS_TURN_LEFT
#endif
#if defined(_WIN32) && defined(CLASS_TURN_RIGHT)
  #undef CLASS_TURN_RIGHT
#endif
#if defined(_WIN32) && defined(CLASS_GO_STRAIGHT)
  #undef CLASS_GO_STRAIGHT
#endif

  enum {
    CLASS_UNKNOWN = 0u,
    CLASS_STOP = 1u,
    CLASS_YIELD = 2u,
    CLASS_SPEED_LIMIT_30 = 3u,
    CLASS_SPEED_LIMIT_50 = 4u,
    CLASS_SPEED_LIMIT_60 = 5u,
    CLASS_SPEED_LIMIT_80 = 6u,
    CLASS_NO_ENTRY = 7u,
    CLASS_NO_PARKING = 8u,
    CLASS_PEDESTRIAN_CROSSING = 9u,
    CLASS_SCHOOL_ZONE = 10u,
    CLASS_CONSTRUCTION = 11u,
    CLASS_TURN_LEFT = 12u,
    CLASS_TURN_RIGHT = 13u,
    CLASS_GO_STRAIGHT = 14u,
  };


  typedef boost::shared_ptr< ::dcas_msgs::TrafficSign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::TrafficSign_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSign_

typedef ::dcas_msgs::TrafficSign_<std::allocator<void> > TrafficSign;

typedef boost::shared_ptr< ::dcas_msgs::TrafficSign > TrafficSignPtr;
typedef boost::shared_ptr< ::dcas_msgs::TrafficSign const> TrafficSignConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::TrafficSign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::TrafficSign_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::TrafficSign_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficSign_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.sign_class == rhs.sign_class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::TrafficSign_<ContainerAllocator1> & lhs, const ::dcas_msgs::TrafficSign_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::TrafficSign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::TrafficSign_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::TrafficSign_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c95b6f353f8d2898545192a2a0de59a6";
  }

  static const char* value(const ::dcas_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc95b6f353f8d2898ULL;
  static const uint64_t static_value2 = 0x545192a2a0de59a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/TrafficSign";
  }

  static const char* value(const ::dcas_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 id\n"
"geometry_msgs/Pose pose\n"
"uint8 sign_class\n"
"\n"
"# Traffic sign classes\n"
"uint8 CLASS_UNKNOWN=0\n"
"uint8 CLASS_STOP=1\n"
"uint8 CLASS_YIELD=2\n"
"uint8 CLASS_SPEED_LIMIT_30=3\n"
"uint8 CLASS_SPEED_LIMIT_50=4\n"
"uint8 CLASS_SPEED_LIMIT_60=5\n"
"uint8 CLASS_SPEED_LIMIT_80=6\n"
"uint8 CLASS_NO_ENTRY=7\n"
"uint8 CLASS_NO_PARKING=8\n"
"uint8 CLASS_PEDESTRIAN_CROSSING=9\n"
"uint8 CLASS_SCHOOL_ZONE=10\n"
"uint8 CLASS_CONSTRUCTION=11\n"
"uint8 CLASS_TURN_LEFT=12\n"
"uint8 CLASS_TURN_RIGHT=13\n"
"uint8 CLASS_GO_STRAIGHT=14\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dcas_msgs::TrafficSign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.sign_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::TrafficSign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::TrafficSign_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sign_class: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sign_class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_TRAFFICSIGN_H
