// Generated by gencpp from file dcas_msgs/VehicleState.msg
// DO NOT EDIT!


#ifndef DCAS_MSGS_MESSAGE_VEHICLESTATE_H
#define DCAS_MSGS_MESSAGE_VEHICLESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Vector3.h>

namespace dcas_msgs
{
template <class ContainerAllocator>
struct VehicleState_
{
  typedef VehicleState_<ContainerAllocator> Type;

  VehicleState_()
    : header()
    , pose()
    , twist()
    , acceleration()
    , steering_wheel_angle_deg(0.0)
    , wheel_speeds_mps()
    , accelerator_pedal(0.0)
    , brake_pedal(0.0)  {
    }
  VehicleState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , twist(_alloc)
    , acceleration(_alloc)
    , steering_wheel_angle_deg(0.0)
    , wheel_speeds_mps(_alloc)
    , accelerator_pedal(0.0)
    , brake_pedal(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef float _steering_wheel_angle_deg_type;
  _steering_wheel_angle_deg_type steering_wheel_angle_deg;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _wheel_speeds_mps_type;
  _wheel_speeds_mps_type wheel_speeds_mps;

   typedef float _accelerator_pedal_type;
  _accelerator_pedal_type accelerator_pedal;

   typedef float _brake_pedal_type;
  _brake_pedal_type brake_pedal;





  typedef boost::shared_ptr< ::dcas_msgs::VehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcas_msgs::VehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleState_

typedef ::dcas_msgs::VehicleState_<std::allocator<void> > VehicleState;

typedef boost::shared_ptr< ::dcas_msgs::VehicleState > VehicleStatePtr;
typedef boost::shared_ptr< ::dcas_msgs::VehicleState const> VehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcas_msgs::VehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcas_msgs::VehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcas_msgs::VehicleState_<ContainerAllocator1> & lhs, const ::dcas_msgs::VehicleState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.twist == rhs.twist &&
    lhs.acceleration == rhs.acceleration &&
    lhs.steering_wheel_angle_deg == rhs.steering_wheel_angle_deg &&
    lhs.wheel_speeds_mps == rhs.wheel_speeds_mps &&
    lhs.accelerator_pedal == rhs.accelerator_pedal &&
    lhs.brake_pedal == rhs.brake_pedal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcas_msgs::VehicleState_<ContainerAllocator1> & lhs, const ::dcas_msgs::VehicleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcas_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::VehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcas_msgs::VehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::VehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcas_msgs::VehicleState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::VehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcas_msgs::VehicleState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcas_msgs::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18b3a6879ecb65c8c32b4cb5c098ed3c";
  }

  static const char* value(const ::dcas_msgs::VehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18b3a6879ecb65c8ULL;
  static const uint64_t static_value2 = 0xc32b4cb5c098ed3cULL;
};

template<class ContainerAllocator>
struct DataType< ::dcas_msgs::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcas_msgs/VehicleState";
  }

  static const char* value(const ::dcas_msgs::VehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcas_msgs::VehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Vector3 acceleration\n"
"float32 steering_wheel_angle_deg\n"
"float32[] wheel_speeds_mps\n"
"float32 accelerator_pedal\n"
"float32 brake_pedal\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dcas_msgs::VehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcas_msgs::VehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.twist);
      stream.next(m.acceleration);
      stream.next(m.steering_wheel_angle_deg);
      stream.next(m.wheel_speeds_mps);
      stream.next(m.accelerator_pedal);
      stream.next(m.brake_pedal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcas_msgs::VehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcas_msgs::VehicleState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "twist: ";
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_wheel_angle_deg: ";
    Printer<float>::stream(s, indent + "  ", v.steering_wheel_angle_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wheel_speeds_mps: ";
    if (v.wheel_speeds_mps.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.wheel_speeds_mps.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.wheel_speeds_mps[i]);
    }
    if (v.wheel_speeds_mps.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accelerator_pedal: ";
    Printer<float>::stream(s, indent + "  ", v.accelerator_pedal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake_pedal: ";
    Printer<float>::stream(s, indent + "  ", v.brake_pedal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCAS_MSGS_MESSAGE_VEHICLESTATE_H
